// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Keywords is the predicate function for keywords builders.
type Keywords func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
